version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: destek_db
      POSTGRES_USER: destek_user
      POSTGRES_PASSWORD: destek_pass
      TZ: Europe/Istanbul
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - destek_network
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: destek-backend-1
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - TZ=Europe/Istanbul
      - UPLOAD_DIR=/app/uploads
      - CORS_ORIGINS=https://destek.tesmer.org.tr,https://destekapi.tesmer.org.tr,https://devdestek.tesmer.org.tr,https://devdestekapi.tesmer.org.tr,https://localhost
      - LDAP_HOST=tesmer.local
      - LDAP_PORT=389
      - LDAP_BASE_DN=OU=TesmerUser,DC=tesmer,DC=local
      - LDAP_BIND_DN=CN=Ldap reader,OU=TesmerUser,DC=tesmer,DC=local
      - LDAP_BIND_PASSWORD=S160682u*
    extra_hosts:
      - "tesmer.local:192.168.0.13"
    depends_on:
      - db
    networks:
      - destek_network

  frontend:
    build: ./frontend
    container_name: destek-frontend-1
    ports:
      - "3005:3000"
    env_file:
      - .env
    environment:
      - TZ=Europe/Istanbul
    networks:
      - destek_network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  destek_network:
    driver: bridge
